### ISSUE TITLE
执行C++版本的程序时，加载模型报错

### ISSUE THREAD

**Issue by Amphetaminewei** [hpc203/Chinese-CLIP-opencv-onnxrun#2]
您好，我在尝试使用C++版本的程序时，遇到了以下错误

```
[ERROR:0] global /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp (1786) handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [ReduceMean]:(/visual/ln_pre/ReduceMean_output_0)
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1797: error: (-2:Unspecified error) in function 'handleNode'
> Node [ReduceMean]:(/visual/ln_pre/ReduceMean_output_0) parse error: OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/include/opencv2/dnn/dnn.inl.hpp:349: error: (-204:Requested object was not found) Required argument "keepdims" not found into dictionary in function 'get'
> 
已放弃 (核心已转储)
```

我使用自己转换的cn_clip模型也是有类似的错误
```
[ERROR:0] global /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp (1786) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Unsqueeze]:(/visual/Unsqueeze_output_0)
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1797: error: (-2:Unspecified error) in function 'handleNode'
> Node [Unsqueeze]:(/visual/Unsqueeze_output_0) parse error: OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1309: error: (-215:Assertion failed) node_proto.input_size() == 1 in function 'handleNode'
> 
```
请问这个问题有什么思路吗，如果不使用OpenCV有其他的C++ onnxruntime部署 cn_clip 的思路嘛

**Comment by hpc203** [comment]
升级opencv版本，或者使用onnxruntime做推理引擎，不用opencv-dnn



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月8日(周五) 下午4:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hpc203/Chinese-CLIP-opencv-onnxrun] 执行C++版本的程序时，加载模型报错 (Issue #2)




 
您好，我在尝试使用C++版本的程序时，遇到了以下错误
 [ERROR:0] global /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp (1786) handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [ReduceMean]:(/visual/ln_pre/ReduceMean_output_0) terminate called after throwing an instance of 'cv::Exception'   what():  OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1797: error: (-2:Unspecified error) in function 'handleNode' &gt; Node [ReduceMean]:(/visual/ln_pre/ReduceMean_output_0) parse error: OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/include/opencv2/dnn/dnn.inl.hpp:349: error: (-204:Requested object was not found) Required argument "keepdims" not found into dictionary in function 'get' &gt;  已放弃 (核心已转储)  
我使用自己转换的cn_clip模型也是有类似的错误
 [ERROR:0] global /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp (1786) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Unsqueeze]:(/visual/Unsqueeze_output_0) terminate called after throwing an instance of 'cv::Exception'   what():  OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1797: error: (-2:Unspecified error) in function 'handleNode' &gt; Node [Unsqueeze]:(/visual/Unsqueeze_output_0) parse error: OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1309: error: (-215:Assertion failed) node_proto.input_size() == 1 in function 'handleNode' &gt;   
请问这个问题有什么思路吗，如果不使用OpenCV有其他的C++ onnxruntime部署 cn_clip 的思路嘛

**Comment by Amphetaminewei** [comment]
> 升级opencv版本，或者使用onnxruntime做推理引擎，不用opencv-dnn
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月8日(周五) 下午4:47 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [hpc203/Chinese-CLIP-opencv-onnxrun] 执行C++版本的程序时，加载模型报错 (Issue #2) 您好，我在尝试使用C++版本的程序时，遇到了以下错误 [ERROR:0] global /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp (1786) handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [ReduceMean]:(/visual/ln_pre/ReduceMean_output_0) terminate called after throwing an instance of 'cv::Exception' what(): OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1797: error: (-2:Unspecified error) in function 'handleNode' &gt; Node [ReduceMean]:(/visual/ln_pre/ReduceMean_output_0) parse error: OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/include/opencv2/dnn/dnn.inl.hpp:349: error: (-204:Requested object was not found) Required argument "keepdims" not found into dictionary in function 'get' &gt; 已放弃 (核心已转储) 我使用自己转换的cn_clip模型也是有类似的错误 [ERROR:0] global /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp (1786) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Unsqueeze]:(/visual/Unsqueeze_output_0) terminate called after throwing an instance of 'cv::Exception' what(): OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1797: error: (-2:Unspecified error) in function 'handleNode' &gt; Node [Unsqueeze]:(/visual/Unsqueeze_output_0) parse error: OpenCV(4.5.0) /home/wangweinan/prj/opencv-4.5.0/modules/dnn/src/onnx/onnx_importer.cpp:1309: error: (-215:Assertion failed) node_proto.input_size() == 1 in function 'handleNode' &gt; 请问这个问题有什么思路吗，如果不使用OpenCV有其他的C++ onnxruntime部署 cn_clip 的思路嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
您好，OpenCV升级到4.7可以嘛，我看在使用CLIP处理图片的时候似乎是用了OpenCV做了一些图片预处理，如果只用onnxruntime的话是不是还需要找其他的库进行一些图片预处理

**Comment by Amphetaminewei** [comment]
您好，我在升级到OpenCV4.9之后消除了上面的错误，还想请教个问题，我使用自己按照cn_clip的GitHub里的教程转换的onnx格式的cn_clip模型仍然存在问题，使用你网盘里的模型是OK的，请问可以分享下这个模型转换和cn_clip使用的转换参数的区别嘛

**Comment by Amphetaminewei** [comment]
我使用onnxruntime做推理驱起来了cn_clip，感谢
